return {
  -- 'kiddos/gemini.nvim',
  -- opts = {
  --   instruction = {
  --     enabled = true,
  --     menu_key = '<C-g>',
  --     prompts = {
  --       {
  --         name = 'Unit Test',
  --         command_name = 'GeminiUnitTest',
  --         menu = 'Unit Test 🚀',
  --         get_prompt = function(lines, bufnr)
  --           local code = vim.fn.join(lines, '\n')
  --           local filetype = vim.api.nvim_get_option_value('filetype', { buf = bufnr })
  --           -- local prompt = 'Context:\n\n```%s\n%s\n```\n\n' .. 'Objective: Write unit test for the above snippet of code\n'
  --           local prompt = 'Context:\n\n```%s\n%s\n```\n\n' .. 'Objective: Viết kiểm thử đơn vị cho đoạn mã trên\n'
  --           return string.format(prompt, filetype, code)
  --         end,
  --       },
  --       {
  --         name = 'Code Review',
  --         command_name = 'GeminiCodeReview',
  --         menu = 'Code Review 📜',
  --         get_prompt = function(lines, bufnr)
  --           local code = vim.fn.join(lines, '\n')
  --           local filetype = vim.api.nvim_get_option_value('filetype', { buf = bufnr })
  --           -- local prompt = 'Context:\n\n```%s\n%s\n```\n\n'
  --           --   .. 'Objective: Do a thorough code review for the following code.\n'
  --           --   .. 'Provide detail explaination and sincere comments.\n'
  --           local prompt = 'Ngữ cảnh:\n\n```%s\n%s\n```\n\n'
  --             .. 'Mục tiêu: Thực hiện đánh giá mã nguồn một cách chi tiết.\n'
  --             .. 'Cung cấp giải thích chi tiết và nhận xét chân thành.\n'
  --
  --           return string.format(prompt, filetype, code)
  --         end,
  --       },
  --       {
  --         name = 'Code Explain',
  --         command_name = 'GeminiCodeExplain',
  --         menu = 'Code Explain',
  --         get_prompt = function(lines, bufnr)
  --           local code = vim.fn.join(lines, '\n')
  --           local filetype = vim.api.nvim_get_option_value('filetype', { buf = bufnr })
  --           -- local prompt = 'Context:\n\n```%s\n%s\n```\n\n'
  --           --   .. 'Objective: Explain the following code.\n'
  --           --   .. 'Provide detail explaination and sincere comments  .\n'
  --           local prompt = 'Ngữ cảnh:\n\n```%s\n%s\n```\n\n'
  --             .. 'Mục tiêu: Giải thích đoạn mã sau.\n'
  --             .. 'Cung cấp giải thích chi tiết và nhận xét chân thành.\n'
  --           return string.format(prompt, filetype, code)
  --         end,
  --       },
  --     },
  --   },
  -- },
}
