return {
  -- {
  --   'stevearc/oil.nvim',
  --   opts = {},
  --   -- dependencies = { { 'echasnovski/mini.icons', opts = {} } },
  --   -- Lazy loading is not recommended because it is very tricky to make it work correctly in all situations.
  --   lazy = false,
  --   config = function()
  --     require('oil').setup()
  --   end,
  -- },
  -- {
  --   'kiddos/gemini.nvim',
  --   opts = {},
  -- },
  -- {
  --   'olimorris/codecompanion.nvim',
  --   opts = {},
  --   dependencies = {
  --     'nvim-lua/plenary.nvim',
  --     'nvim-treesitter/nvim-treesitter',
  --   },
  -- },
}
